### ISSUE TITLE
chore(deps): version bump to 6.12.2

### ISSUE THREAD

**Issue by supposedlysam-bb** [AppsFlyerSDK/segment-appsflyer-ios#129]
The `appsflyer_sdk` project is currently using version `6.12.2` but I cannot get my dependencies to play nicely unless this package's dependency is also bumped.

## Pod Update Error
```bash
[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    appsflyer_sdk (from `.symlinks/plugins/appsflyer_sdk/ios`) was resolved to 6.8.0, which depends on
      AppsFlyerFramework (= 6.12.2)

    bluebottle_flutter_segment (from `.symlinks/plugins/bluebottle_flutter_segment/ios`) was resolved to 4.0.0, which depends on
      segment-appsflyer-ios (= 6.12.1) was resolved to 6.12.1, which depends on
        segment-appsflyer-ios/Main (= 6.12.1) was resolved to 6.12.1, which depends on
          AppsFlyerFramework (= 6.12.1)
```

![image](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/assets/61704697/9d96a4ed-e2cc-4360-8bb5-8632aa8417e3)

**Comment by Samin-roadsurfer** [comment]
@supposedlysam-bb hi, any answer on how to fix this issue?

**Comment by supposedlysam-bb** [comment]
@Samin-roadsurfer they said they will see if they can pull it in to get it worked on in the coming weeks. What I've done in the meantime (not ideal) is to fork the package and do the bump myself, then reference my GitHub hosted one inside of my Podfile. Once they do a update I'll switch back to the Cocoapods version.

**Comment by Samin-roadsurfer** [comment]
thank you for your response @supposedlysam-bb :)
