### ISSUE TITLE
Missing versions from CocoaPods

### ISSUE THREAD

**Issue by brianmichel** [AppsFlyerSDK/segment-appsflyer-ios#13]
It seems that all versions after 1.1.7 are missing from CocoaPods.

Can you please push these specs to trunk so others may easily use them? 

Thanks!

**Comment by brianmichel** [comment]
@f2prateek can you help?

**Comment by f2prateek** [comment]
@brianmichel Sorry, Segment doesn't maintain this integration and we don't have access to making updates this repository or cocoapods releases for Appsflyer.

I can confirm what you are seeing. The latest version on cocoapods is 1.1.7 https://cocoapods.org/pods/segment-appsflyer-ios while on Github it is 1.1.11 https://github.com/AppsFlyerSDK/segment-appsflyer-ios/releases/tag/v1.1.11. The right solution is here is for someone from AppsFlyer (likely @af-fess) to publish the version to CocoaPods.

If you don't hear back from @af-fess, I'd recommend writing into AppsFlyer support directly. They'll be able to get it surfaced to the right people on their time.

**Comment by f2prateek** [comment]
While obviously the right solution is for the releases to be published to CocoaPods, in the meantime, you can also do:

```
pod 'segment-appsflyer-ios', :git => 'https://github.com/AppsFlyerSDK/segment-appsflyer-ios.git', :tag => '1.1.11'
```

**Comment by af-fess** [comment]
@brianmichel hi, yes, we stopped update Cocoapods after 1.1.7. Please look on this pull request: https://github.com/AppsFlyerSDK/segment-appsflyer-ios/pull/12

Thanks,

**Comment by f2prateek** [comment]
hey @af-fess 

By not releasing the new versions to cocoapods you're making it unnecessarily harder for consumers that don't need the `use_frameworks!` flag.

For consumers that do need the `use_frameworks!` flag and run into the transitive static library issue, the workarounds you've suggested are now outdated. See https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-259402257. Here's what the implementation looks like https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/14.

**Comment by f2prateek** [comment]
👍 , wasn't sure if you were aware.
