### ISSUE TITLE
Update version_appsflyerLib to '6.14.2' to include PrivacyInfo file

### ISSUE THREAD

**Issue by MarcinusX** [AppsFlyerSDK/segment-appsflyer-ios#135]
Hey AppsFlyer team!

Could you please upgrade this package (`segment-appsflyer-ios`) to use a version of `AppsFlyerFramework` with the PrivacyInfo manifest file?
You've introduced it in core lib in version `6.14.0` but this package is still using `6.13.1`.

It would be highly appreciated 🙏

Thank you!

**Comment by morisgateno-appsflyer** [comment]
Hi @MarcinusX .
It's out :boom:
Thanks :)
Moris
