### ISSUE TITLE
SPM Support?

### ISSUE THREAD

**Issue by dannyhertz** [AppsFlyerSDK/segment-appsflyer-ios#30]
Hello! Hoping to integrate your library but we only support SPM. Is there any timeline when you will support it?

**Comment by af-vs** [comment]
Hi @dannyhertz!

For a while, SPM didn't support packages containing binary frameworks. I can see from [this message](https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/94#issuecomment-657974958) that this seems to have been resolved recently and I believe we may reconsider this once again shortly.

Thank you for raising this up!

**Comment by dannyhertz** [comment]
Hey! Just checking in to see if there are any updates on SPM support!

**Comment by af-fess** [comment]
So far we try to solve it for regular SDK. More details you can find here: https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/143

**Comment by crtgregoric** [comment]
Any update on this?

**Comment by af-margot** [comment]
Hi @crtgregoric, 
Not yet, we are waiting for Xcode 12.5.

**Comment by dannyhertz** [comment]
12.5 rc is out. Any ETA on SPM support please?

**Comment by morluna** [comment]
Hi @af-margot looks like `master` already has SPM support and we've verified it works on a branch. We are really looking to integrate it because we are using other Segment plugins (via SPM) that depend on Segment. This makes it messy because we have the Segment wanting to get added as a SPM and Pod. 

Any word?

**Comment by af-margot** [comment]
Hi @morluna, 
Indeed we have SPM Support now. I'm not sure to understand the issue here. It's not working for you?

**Comment by morluna** [comment]
@af-margot no issue really, it's more about having a dedicated release for it. Our team doesn't feel comfortable adding the AppsFlyer plug-in pointing at `master`.

The latest release for is currently 6.3.0, but SPM support is not in that release.

**Comment by af-margot** [comment]
Hi @morluna, 
Got you! We will release 6.3..2 soon, it should be today or tomorrow. This release will support SPM.

**Comment by af-margot** [comment]
@morluna ,

Here is the new [release](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/releases/tag/6.3.2)!
