### ISSUE TITLE
Compatibility with latest segment SDK

### ISSUE THREAD

**Issue by jwaldrip** [AppsFlyerSDK/segment-appsflyer-ios#34]
I believe the interface changed in the latest version of segment.

Getting the following error when trying to compile:

```
▸ Compiling SEGAppsFlyerIntegrationFactory.m
❌  /Users/administrator/builds/2/builds/gigsmart/projects/monorepo/mobile/apps/requester/ios/Pods/segment-appsflyer-ios/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegrationFactory.h:10:9: 'Segment/SEGIntegrationFactory.h' file not found
#import <Segment/SEGIntegrationFactory.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
▸ Compiling SEGAppsFlyerIntegration.m
❌  /Users/administrator/builds/2/builds/gigsmart/projects/monorepo/mobile/apps/requester/ios/Pods/segment-appsflyer-ios/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegration.h:10:9: 'Segment/SEGAnalytics.h' file not found
#import <Segment/SEGAnalytics.h>
```

**Comment by cjpete** [comment]
I'm also seeing this. I believe it's because the underlying dependency is now called `Analytics` not `Segment`. Changing the header file imports seems to resolve the build errors.

**Comment by af-fess** [comment]
We got an update from Segment team to update to [4.1.0](https://github.com/segmentio/analytics-ios/releases/tag/4.1.0).
One of their fixes where `Renames module to Segment from Analytics`: https://github.com/segmentio/analytics-ios/pull/942
 You can find in our [podspec](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/master/segment-appsflyer-ios.podspec#L21).

The PR: #33

**Comment by af-fess** [comment]
You can use [6.0.3](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/releases/tag/6.0.3)
