### ISSUE TITLE
non-organic install on ios 14

### ISSUE THREAD

**Issue by Max-Job** [AppsFlyerSDK/segment-appsflyer-ios#38]
How simulate a non-organic install on ios 14? I use [this guide](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-integration-guide-for-developers/), but it's not working for me - always get organic install.
My app ask permission for **Privacy - Tracking Usage Description** and if I allow it, I get organic install anyway.

some details:
iphone xs max 
ios 14.2
xcode 12.2 beta 4

segment-appsflyer-ios (6.1.0)
Analytics (4.1.1)
AppsFlyerFramework (6.0.8)

**Comment by Max-Job** [comment]
should i use SKAdNetworkItems in info.plist? which dictionaries of SKAdNetworkItems can i use for simulate a non-organic install? where i can get it from real ad company?

**Comment by af-margot** [comment]
Hi @Max-Job , 

For attribution issues, please contact AppsFlyer support at support@appsflyer.com.
Thank you!

**Comment by Max-Job** [comment]
@af-margot thanks
