### ISSUE TITLE
Update to AppsFlyer SDK 6.0.5 for Kids App Support

### ISSUE THREAD

**Issue by jaredsilver** [AppsFlyerSDK/segment-appsflyer-ios#39]
👋  Greetings!

Pursuant to recent changes in App Store submission criteria, AppsFlyer version 6.0.5 is a necessary update for apps listed in the Kids category to be submitted. Any Kids category apps currently using this package will be unable to submit or update their apps until 6.0.5 support.

See here for further details: https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS#additional-apis-kids-apps

Is there any ETA on when this package will be upgraded to support 6.0.5?

Thank you!

**Comment by af-fess** [comment]
hey @jaredsilver 
We test our beta version with few native SDK clients.
 
We want to be sure that Apple does not reject the app. Will be great if you can test it.

If it goes well, we will publish this version to Production and will update the Segment wrapper

**Comment by jaredsilver** [comment]
@af-fess Awesome, thanks! That sounds great. To clarify, do you have an existing beta release with the iOS 6.0.5 SDK that we could pull in? We'd be happy to submit with it sometime today if so!

**Comment by af-fess** [comment]
@jaredsilver this is a pod you can make a try:

```
pod 'appsflyer-apple-sdk-qa/NoIDFA', '6.1.1.25'
```

**Comment by jaredsilver** [comment]
Great news, we've been approved in the App Store using `pod 'appsflyer-apple-sdk-qa/NoIDFA', '6.1.1.25'`! Thanks, @af-fess. I'll close this issue now 👍

**Comment by af-fess** [comment]
@jaredsilver please use production version:
It could be installed with Cocoapods:
```
 pod 'AppsFlyerFramework/Strict','6.1.1'
```

**Comment by af-fess** [comment]
We also decided to use Strict name instead No-IDFA
