### ISSUE TITLE
Attribution Tracking may throw exceptions

### ISSUE THREAD

**Issue by f2prateek** [AppsFlyerSDK/segment-appsflyer-ios#4]
The `installData` dictionary provided to `onConversionDataReceived` may not always contain all of these being used in the [code](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/master/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegration.m#L119-L121).

Here's a real example of `installData`:

```
installData: {
    "af_message" = "organic install";
    "af_status" = Organic;
}
```

This will certain  values in the campaign dictionary to be set to `nil`, and [this specific line](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/master/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegration.m#L124-L127) will throw an error.

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
```

The fix would be to:
1. Clean up the campaign dictionary of nils prior to creating the properties dictionary.
2. Add fallbacks for values in the [spec](https://segment.com/docs/spec/mobile/#install-attributed). e.g. `@"source": installData[@"media_source"]` should be `@"source": installData[@"media_source"] ?: installData[@"af_status"]`.

**Comment by af-vs** [comment]
Closing this legacy issue. If still relevant please re-open. Thanks!
