### ISSUE TITLE
ios 14 in 6.0.4

### ISSUE THREAD

**Issue by Max-Job** [AppsFlyerSDK/segment-appsflyer-ios#40]
why your last release 6.0.4 less than 6.1.0? what about ios 14 in 6.0.4?

**Comment by af-margot** [comment]
Hi @Max-Job, 

6.1.0 was a wrong version name, sorry about the confusion!
However, 6.0.4 contains all the features that 6.1.0 had.

**Comment by Max-Job** [comment]
ok. thank you)
