### ISSUE TITLE
Do you hava a plan to support XCFramework?

### ISSUE THREAD

**Issue by muukii** [AppsFlyerSDK/segment-appsflyer-ios#43]
Do you have a plan to support XCFramework?
Because we will need it to build an app for Simulator with Arm64.

Thank you.

**Comment by af-fess** [comment]
hey, 
Maybe this conversation can help you: https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/143

**Comment by af-fess** [comment]
Possible duplicate of https://github.com/AppsFlyerSDK/segment-appsflyer-ios/issues/30

**Comment by muukii** [comment]
Oh thanks!
