### ISSUE TITLE
Events do not appear on segment panel

### ISSUE THREAD

**Issue by Lucasdsk** [AppsFlyerSDK/segment-appsflyer-ios#47]
It seems that some events are sent but they were not tracked by segment.io.
![image](https://user-images.githubusercontent.com/7729844/106340662-4c8ff600-6279-11eb-9ef3-4b3791a17e52.png)

On segment panel none events were delivered:

![image](https://user-images.githubusercontent.com/7729844/106340553-f458f400-6278-11eb-9690-21ea549e7262.png)

This is our `AppDelegate.m`: https://gist.github.com/Lucasdsk/443394d12171614bc8944bcd540ef78a
Also in `AppDelegate.h` I have:
`#import "SEGAppsFlyerIntegrationFactory.h"`

Am I missing something?

**Comment by af-margot** [comment]
Hi @Lucasdsk, 
The code looks fine.
I'm not familiar with the **Delivery Trends** tool from Segment, but it seems that it only supports [server-side events](https://segment.com/docs/connections/event-delivery/). 
If you want to check if events from the app are sent to Segment, you can check in the Segment Dashboard in Sources/Debugger. 
![Xnip2021-01-30_20-10-46](https://user-images.githubusercontent.com/48682256/106365674-50824d80-6337-11eb-9a2f-5f7a1d73c12c.jpg)
Hope this helps!

If you think there is another issue, please contact support@appsflyer.com. You can send them full logs and explain when the issue started, version...
Thank you!

**Comment by Lucasdsk** [comment]
hey @af-margot , I had to use the package `react-native-appsflyer` instead of this one because it wasn't tracking the events.
