### ISSUE TITLE
 Is there Xamarin binding for this repo

### ISSUE THREAD

**Issue by pmahend1** [AppsFlyerSDK/segment-appsflyer-ios#52]
# Question

## Plugin Version
Any

## On what Platform are you having the issue?
iOS through Xamarin forms

## What did you do?
Switching to segment

We have been using Appsflyer Xamarin nuget. So now we are switching to Segment.
We noticed there is no Xamarin counterpart for that. 
So what should be the way to go ?

Can we use Segment library along with Appsflyer. 

Are there plans to have Xamarin library for this repo?

If not how can we route installation/attribution events through Segment.

I notice we have `AppsFlyerLib.Instance.Start` in the Appsflyer Xamarin library , do we need to have `AppsFlyerConversionDelegate` instead of that for this approach.

**Comment by af-margot** [comment]
Please see the answer [here](https://github.com/AppsFlyerSDK/appsflyer-segment-android-plugin/issues/40#issuecomment-796988669)
