### ISSUE TITLE
Warning in Xcode 12.x for version 6.2.3

### ISSUE THREAD

**Issue by shilmista** [AppsFlyerSDK/segment-appsflyer-ios#54]
As of `6.2.3` we've started seeing this warning when building on Xcode 12.x

```
ld: warning: dylib (/Users/Shared/web/mobile-iossdk/Swift/Carthage/Build/iOS/SegmentAppsFlyeriOS.framework/SegmentAppsFlyeriOS) was built for newer iOS version (12.0) than being linked (11.0)
```

Our deployment target is iOS 11.0. It doesn't seem to affect running the app, but I'd to see if there's a workaround / fix for this.

**Comment by af-margot** [comment]
Hi @shilmista,
Thank you for reaching out! 
It's because we build it with deployment target sets to iOS 12. We will change it for the next release. 
In the meantime, it should not be an issue. But let us know if it is.
