### ISSUE TITLE
"Install Attributed" tracked on every app launch

### ISSUE THREAD

**Issue by arabold** [AppsFlyerSDK/segment-appsflyer-ios#6]
I'm testing my integration of AppsFlyer with Segment on iOS. My issue is that the AppFlyer integration is tracking a "Install Attributed" event on every app launch. I understand from the AppsFlyer docs that it's expected that `onConversionDataReceived` gets invoked every time, but I fail to understand why or if it's intended that there's also an `Install Attributed` tracked every single time. This just doesn't make sense to me on every app launch. Shouldn't this happen _only_ on new installs?

Here're the relevant pods used:

```
  - Analytics (3.5.2)
  - AppsFlyerFramework (4.5.9)
  - segment-appsflyer-ios (1.1.7):
    - Analytics (~> 3.1)
    - AppsFlyerFramework (~> 4.5)
```

My Segment code looks like the following. Note the `config.trackAttributionData = YES` to enable automatic attribution tracking like described in the Segment [CHANGELOG.md](https://github.com/segmentio/analytics-ios/blob/master/CHANGELOG.md#version-350-12th-september-2016):

``` objc
    SEGAnalyticsConfiguration *config = [SEGAnalyticsConfiguration configurationWithWriteKey:@"xxxxxxxx"];

    // Track with AppsFlyer
    [config use:[SEGAppsFlyerIntegrationFactory instance]];

    config.enableAdvertisingTracking = YES;
    config.trackApplicationLifecycleEvents = YES;
    config.trackDeepLinks = YES;
    config.trackPushNotifications = YES;
    config.trackAttributionData = YES;

    [SEGAnalytics setupWithConfiguration:config];
```

As stated, the `SEGAppsFlyerIntegration`'s `onConversionDataReceived` is triggered on every app launch. This happens regardless whether I set the `trackAttributionData` to `YES` or `NO`.  Is this really intended and if yes, is there a way to prevent this without disabling the AppsFlyer integration completely? Or what am I missing here?

_UPDATE_: Maybe worth mentioning that I'm testing this on a simulator and the tracked attribution data is "Organic".

Thanks,
Andre

**Comment by arabold** [comment]
In the meantime I've figured out that the `trackAttributionData` property of the `SEGAnalyticsConfiguration` is not respected by `segment-appsflyer-ios`. Instead I can configure attribution tracking in the Segment web user interface. This seems reasonable but it's also a bit confusing --> _this should be explained in the docs more explicit_

However, my initial question still stands: Is it intended that `Install Attributed` is tracked on every app launch instead of only during the installation?

**Comment by af-golan** [comment]
@arabold Currently it is intended to send "Install Attributed" on each launch.
We will review your requests..Thanks.

**Comment by f2prateek** [comment]
@arabold the `trackAttributionData`  on `SEGAnalyticsConfiguration` is meant for the `analytics-ios` SDK to track install information using our mobile service (and not used by integrations). This is meant to be used with tools that are integrated server side so you don't need to bundle tools for this information.

Integrations that are able to do this on the client device (such as AppsFlyer) have settings in their integrations pane. These will use the tool's client side SDK to retrieve the attribution infomration.

The current implementation does track on every app launch. One way this could be improved is by saving a preference in the integration, which could ensure only one event is tracked per install. Until then, I'd recommend counting the event only once per anonymous id/device id.

**Comment by arabold** [comment]
Thanks, @f2prateek, for getting back to me on this. Right now I've disabled automated attribution tracking by the plugin and rely on my own implementation that does exactly what you suggested: store a status flag in the app settings to distinguish first start (= a new installation) from subsequent starts. It works pretty reliably and I'm happy with it. In this context I've also opened feature request #7.

It would be great if something like that makes it in the official distribution one day 👍

**Comment by mattfeury** [comment]
agreed that this seems like surprising behavior. aware that we can do this ourselves, but to me this seems like an obvious feature of this integration. the install can only be attributed once on initial run,  so why bother sending it?

**Comment by af-fess** [comment]
it makes sense, will be fixed shortly.

**Comment by af-fess** [comment]
fixed, Install Attributed" will fire once on 1st launch only (V1.1.13)
