### ISSUE TITLE
'SEGAppsFlyerIntegrationFactory.h' file not found when using Carthage

### ISSUE THREAD

**Issue by adrgrondin** [AppsFlyerSDK/segment-appsflyer-ios#63]
We are migrating our Cocoapods `segment-appsflyer-ios` `6.2.61` to version `6.3.0` with Carthage and XCFramework on Xcode 12.5. The steps in the installation for Swift seems outdated, we directly encounter the error `'SEGAppsFlyerIntegrationFactory.h' file not found` in our bridging header. Both `Segment.xcframework` and `SegmentAppsFlyeriOS.xcframework` are imported in our project. 
Also is a Swift Package Manager version coming soon? segment-appsflyer-ios is one of the last dependencies in our project that still does not support SPM.

**Comment by adrgrondin** [comment]
Hi @af-margot ,

Thank you for the answer. Waiting for updates of this issue then.

**Comment by af-margot** [comment]
Hi @adrgrondin, 

We are still checking for Carthage. But if you want to use SPM, you should be able to use it using the branch `master`.
