### ISSUE TITLE
crash in _afsdk_print_dependencies

### ISSUE THREAD

**Issue by ir2pid** [AppsFlyerSDK/segment-appsflyer-ios#68]
We get a spike in crashes.

**Dependencies used:**

        <framework src="Analytics" type="podspec" spec="~> 3.7.0" />
        <framework src="Segment-Amplitude" type="podspec" spec="~> 3.0.1" />
        <framework src="segment-appsflyer-ios" type="podspec" spec="6.3.0" />

**Crash log:**

![image](https://user-images.githubusercontent.com/907075/124885739-de8fed80-dfd3-11eb-8480-a849ec3d49fc.png)

**Comment by af-margot** [comment]
Hi @ir2pid, 
Thank you for reaching out!
We will look into this and get back to you. 
Is this only happening with` segment-appsflyer-ios 6.3.0` or does it happened with older versions also ?

**Comment by ir2pid** [comment]
We didn't use segment-appsflyer before. Were using the original Appsflyer sdk.

**Comment by morluna** [comment]
We're also seeing a spike in crashes:

We're using `segment-appsflyer-ios 6.3.2` as a Swift Package.

<img width="1216" alt="Screen Shot 2021-07-09 at 3 15 25 PM" src="https://user-images.githubusercontent.com/8826948/125131508-7ec73e80-e0c8-11eb-8200-68a3db2d5a71.png">

**Comment by vasuagrawal84** [comment]
Hi @af-margot, we're also seeing this error a lot in our reporting when using segment-appsflyer-ios `6.3.2`. Is there any update in the investigations?

```
Role:               Foreground
OS Version:         iOS 14.6
Exception Type:     EXC_BAD_ACCESS 
Exception Subtype:  KERN_INVALID_ADDRESS


EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x100000000.

0  libobjc.A.dylib         _mapStrHash(_NXMapTable*, void const*)
1  libobjc.A.dylib         _NXMapMember(_NXMapTable*, void const*, void**)
2  libobjc.A.dylib         getClass_impl(char const*)
3  libobjc.A.dylib         getClassExceptSomeSwift(char const*)
4  libobjc.A.dylib         _look_up_class
5  <AppName>        _afsdk_print_dependencies (<AppName>)
6  <AppName>        -[AppsFlyerLib __startWithCompletionHandler:] (<AppName>)
7  <AppName>        -[SEGAppsFlyerIntegration start] (SEGAppsFlyerIntegration.m:138:5)
8  CoreFoundation          ___invoking___
9  CoreFoundation          -[NSInvocation invoke]
10 CoreFoundation          -[NSInvocation invokeWithTarget:]
11 <AppName>        -[SEGIntegrationsManager invokeIntegration:key:selector:arguments:options:] (SEGIntegrationsManager.m:668:5)
12 CoreFoundation          ___NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__
13 CoreFoundation          -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
14 <AppName>        -[SEGIntegrationsManager forwardSelector:arguments:options:] (SEGIntegrationsManager.m:573:5)
15 <AppName>        __seg_dispatch_specific_block_invoke (SEGUtils.m:494:13)
16 libdispatch.dylib       __dispatch_call_block_and_release
17 libdispatch.dylib       __dispatch_client_callout
18 libdispatch.dylib       __dispatch_lane_serial_drain$VARIANT$mp
19 libdispatch.dylib       __dispatch_lane_invoke$VARIANT$mp
20 libdispatch.dylib       __dispatch_workloop_worker_thread
21 libsystem_pthread.dylib __pthread_wqthread
```

**Comment by eshkoliGilad** [comment]
Update:
This issue has been fixed by the R&D at the native SDK side and is currently being tested by our QA team. 
It should be available on the next plugin release.
Current ETA for new plugin release is at the end of July.

**Comment by af-margot** [comment]
Hi, 

Please update to `6.3.4`. It should fix the issue !
