### ISSUE TITLE
Feature: Call app's `onConversionDataReceived` even if attribution tracking is enabled

### ISSUE THREAD

**Issue by arabold** [AppsFlyerSDK/segment-appsflyer-ios#7]
I have implemented my own `onConversionDataReceived` function, registered it at the `AppsFlyerTracker` and it gets successfully invoked automatically on app launch as expected. However, when enabling attribution tracking in the AppsFlyer setting in the Segment web interface, the `segment-appsflyer-ios` library overwrites my delegate and puts it's own there instead. Hence my function doesn't get invoked anymore. The only way around this is to disable automatic attribution tracking for AppsFlyer.

As I want to perform additional operations besides the basic tracking, I have to implement everything myself. What I would like is to enable the automatic tracking (toggle Segment/AppsFlyer's attribution tracking to _enabled_) but still have an option to invoke my own delegate function afterwards.

**Comment by BFMarks** [comment]
Share your code

**Comment by af-fess** [comment]
fixed, Install Attributed" will fire once on 1st launch only
