### ISSUE TITLE
'AppsFlyerLib/AppsFlyerLib.h' file not found

### ISSUE THREAD

**Issue by Hans92** [AppsFlyerSDK/segment-appsflyer-ios#73]
`segment-appsflyer-ios` version v6.4.0 is not compiling with Xcode 13.1. There is some issue with importing AppsFlyerLib with SPM in `SEGAppsFlyerIntegration.h`:
```
'AppsFlyerLib/AppsFlyerLib.h' file not found
```

Steps to reproduce:  
- clone the repo
- open `Package.swift` in Xcode 13.1
- try to build

**Comment by af-margot** [comment]
Hi @Hans92, 

We will check this. The issue is only happening with Xcode 13.1 if I understand correctly?

**Comment by Hans92** [comment]
@af-margot I can confirm that it also occurs with Xcode 13.0. First build always fails but building it a second time succeeds.

**Comment by morluna** [comment]
@af-margot this is also happening for us using `segment-appsflyer-ios` version 6.3.4 and building with our release configuration only

![Screen Shot 2021-11-12 at 1 29 35 PM](https://user-images.githubusercontent.com/8826948/141530605-c0286c93-55ac-4bdc-904e-50412c39531d.png)
.

**Comment by georgenavarro** [comment]
I was having the same issue where first build failed, which was blocking my CI/CD system from doing clean builds. However if I changed the package file to include the AppsFlyer XCFramework directly as a binary target the problem went away:

**Comment by TimurAsayonok** [comment]
I can confirm it happens with the Swift Package Manager version.
`v.6.4.4`

**Comment by mattlangtree** [comment]
I encountered this issue on `v6.4.0` and for me the issue was that part of the AppsFlyer framework files was in git lfs and I hadn't yet pulled the necessary files down. If you're in a similar case, do `cat .gitattributes` on the root of your project and if AppsFlyer is mentioned, perhaps you're in a similar situation. If that file doesn't exists or AppsFlyer isn't listed, this might not help you.

To get the Git LFS files, run: 
```
brew install git-lfs
git-lfs install
git-lfs pull
```

**Comment by rwgrier** [comment]
@af-margot any update on this issue? I'm seeing it as well. The build failures are inconsistent, but the error is always the same:

```
'AppsFlyerLib/AppsFlyerLib.h' file not found
```

I'm attempting to use v6.5.2.

**Comment by abubakrj** [comment]
The same happening with Xcode 13.2.1. I am using version 6.5.2
