### ISSUE TITLE
Module map instead of Bridging-Header

### ISSUE THREAD

**Issue by TimurAsayonok** [AppsFlyerSDK/segment-appsflyer-ios#74]
Hello,
do you have any plans for not to use `Bridging-Header`?
Main AppsFlyer SDK don't use it so it make big sense not to use it here.

Thanks.

**Comment by TimurAsayonok** [comment]
@af-margot Hello,
Could you check this question? =)

thanks!

**Comment by af-margot** [comment]
Hi @TimurAsayonok , 

This is not currently in our plans, but we will take it into account and try to add it to one of the next releases.

**Comment by TimurAsayonok** [comment]
@af-margot thanks for replying, have a nice new year ☺️
I will close it i think!
