### ISSUE TITLE
wait for customer user id to set in AppsFlyer

### ISSUE THREAD

**Issue by priyankabncs** [AppsFlyerSDK/segment-appsflyer-ios#83]
Hello,

I want to set the customer user id in AppsFlyer and need to delay the initialization of AppsFlyer. See this document of AppsFlyer.
https://support.appsflyer.com/hc/en-us/articles/207032016-Customer-user-ID-field-CUID-#ios-sdk-developer-instructions

I have called identify method but it is after `setupWithConfiguration` so before this AppsFlyer get initialized and started, so I can't map install event with user-id

How can I achieve this using this library? Can you please help me ASAP

Thanks & regards,
Priyanka

**Comment by mrbungie** [comment]
We're experimenting the same thing, any event that occurs during a session that started with a blank/null customer_user_id appears in segment without that field. 

Shouldn't a segment identify call reinitialize Appsflyer so events are sent with the correct customer_user_id?

**Comment by morisgateno-appsflyer** [comment]
Hi.
Thanks for reaching out, and sorry for the delayed response.
I am running the command: Analytics.shared().identify("#####") after : Analytics.setup(with: config).
I think this is what you meant.
But, on my side, it works perfectly fine. I see the SDK is triggered with the "appUID":"#####".
Can you maybe provide some more information?
Thanks,
Moris.
