### ISSUE TITLE
GitGub CI fails

### ISSUE THREAD

**Issue by VitalikKizlov** [AppsFlyerSDK/segment-appsflyer-ios#89]
Compiles successfully locally but on CI it fails with such error:

`fatal error: module 'segment_appsflyer_ios' in AST file '/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2R0I1PIXHKYD2/segment_appsflyer_ios-RKME7K7ITP56.pcm' (imported by AST file '/Users/runner/Library/Developer/Xcode/DerivedData/qcast-bejqdshzoluhsigsdygsoeunqust/Build/Intermediates.noindex/ArchiveIntermediates/Quartr/PrecompiledHeaders/qcast-Bridging-Header-swift_QGQETLNNGPLD-clang_2R0I1PIXHKYD2.pch') is not defined in any loaded module map file; maybe you need to load '/Users/runner/Library/Developer/Xcode/DerivedData/qcast-bejqdshzoluhsigsdygsoeunqust/Build/Intermediates.noindex/ArchiveIntermediates/Quartr/IntermediateBuildFilesPath/GeneratedModuleMaps-iphoneos/segment-appsflyer-ios.modulemap'?`

Any ideas what is wrong ?

**Comment by hunterleebrown-cbs** [comment]
bounce 👆
