### ISSUE TITLE
Compatibility with analytics-swift from Segment

### ISSUE THREAD

**Issue by PaulWen** [AppsFlyerSDK/segment-appsflyer-ios#99]
Hi, is this SDK compatible with the [analytics-swift](https://github.com/segmentio/analytics-swift) SDK from Segment?

**Comment by morisgateno-appsflyer** [comment]
Hello @PaulWen.
We are currently working with the preview library - analytics-ios.
We are considering moving to the new library - analytics-swift.
Hope soon I will have a more concrete answer for you.
Thanks.

**Comment by skydivedan** [comment]
Is there any movement on this? The old segment library hasn't been updated since last February, as it looks like all further effort is going towards Analytics-Swift.
